version: "3.1"
services:
  # mongodb://root:example@localhost:27017
  mongodb:
    image: "mongo:6.0.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: iweb
    ports:
      - "27017:27017"

  # http://localhost:8001
  a2reservasrest:
    build: A2reservasREST
    environment:
      mongo_url: "mongodb://root:example@mongodb:27017"
    env_file:
      - A2reservasREST/.env
    ports:
      - "8001:8000"
  # http://localhost:8002
  a2viviendasrest:
    build: A2viviendasREST
    environment:
      mongo_url: "mongodb://root:example@mongodb:27017"
      mongo_database: "iweb"
      mongo_collection: "houses"
    ports:
      - "8002:8000"
  # http://localhost:8003
  a2datosabiertosrest:
    build: A2datosabiertosREST
    ports:
      - "8003:8000"
  # http://localhost:8004
  a2autenticacionrest:
    build: A2autenticacionREST
    ports:
      - "8004:8000"
  # http://localhost
  # a2cliente:
  #   build: A2clienteREST
  #   ports:
  #     - "80:3000"
  #   environment:
  #     RESERVAS_BASE_PATH: "http://a2reservasrest:8000"
  #     VIVIENDAS_BASE_PATH: "http://a2viviendasrest:8000"
  #     DATOSABIERTOS_BASE_PATH: "http://a2datosabiertosrest:8000"
  #     CLOUDINARY_CLOUD_NAME: "demo"
  #     CLOUDINARY_UPLOAD_PRESET: "docs_upload_example_us_preset"
  #   volumes:
  #     - ./A2datosabiertosREST:/A2datosabiertosREST
  