# fly.toml file generated for a2reservas on 2022-12-29T20:02:58+01:00

app = "a2reservas"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  mongo_collection="houses"
  mongo_database="iweb-windbnb"
  paypal_url="https://api-m.sandbox.paypal.com"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
